<../mkconfig

TARG=devdraw

XFILES=\
	init.$O\
	window.$O\

OFILES=\
	drawfcall.$O\
	fs.$O\
	main.$O\
	$LIBIXP\
	${XFILES:%=x11/%}\

XHFILES=\
	inc.h\

HFILES=\
	devdraw.h\
	drawfcall.h\
	${XHFILES:%=x11/%}\

LIBS=	9 draw memdraw memlayer

BIN=$ROOT/$OBJDIR/bin

<$ROOT/mkfiles/mkone-$SHELLTYPE
